linters:
    csslint:
        ignore: 'box-model'
    stylelint:
        fixer: true
    eslint:
      config: './eslint.config'
    phpcs:
      extensions: 'php,css'

files:
  ignore:
    - 'normalize.css'

fixers:
    enable: true
