linters:
    csslint:
      ignore: 'box-model'
    stylelint:
    eslint:
      config: './eslint.config'
      fixer: true
      ignore: 'box-model'
    phpcs:
      extensions: 'php,css'

files:
  ignore:
    - 'normalize.css'

fixers:
    enable: true
